import Footer from './components/Footer'
import Nav from './components/Nav'
import Provider from './context/AuthContext'
import ToasterContext from './context/ToasterContext'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My-Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToasterContext />
          <Nav />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
